# Generated by Django 3.0.3 on 2020-02-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.BaseModel')),
                ('first_name', models.CharField(max_length=20, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=20, verbose_name='LastName')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            bases=('accounts.basemodel',),
        ),
    ]
