# Generated by Django 3.0.3 on 2020-02-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.BaseModel')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
            bases=('accounts.basemodel',),
        ),
    ]
